# Generated by Django 3.2.7 on 2021-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0014_auto_20210916_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('started_datetime', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('winner', models.CharField(blank=True, choices=[('R', 'Radiant'), ('D', 'Dire')], max_length=1, null=True)),
                ('dire_team', models.ManyToManyField(related_name='matches_as_dire', to='heroes.Hero')),
                ('radiant_team', models.ManyToManyField(related_name='matches_as_radiant', to='heroes.Hero')),
            ],
        ),
    ]
