# Generated by Django 3.2.7 on 2021-09-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonuser',
            name='user_role',
        ),
        migrations.AddField(
            model_name='commonuser',
            name='user_roles',
            field=models.ManyToManyField(related_name='users', to='user_management.Role'),
        ),
    ]
