# Generated by Django 3.2.7 on 2021-09-08 12:25

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_auto_20210907_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=user_management.models.user_directory_path),
        ),
    ]
