# Generated by Django 3.2.7 on 2021-09-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_commonuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonuser',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='commonuser',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
