version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/code
    ports:
      - "8000:8000"

  redis:
    image: redis

  celery:
    build:
      context: .
    command: celery -A dota_heroes worker -l INFO
    volumes:
      - .:/code
    environment:
      - C_FORCE_ROOT=true
    depends_on:
      - redis
      - web
