# Generated by Django 3.2.7 on 2021-09-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('heroes', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.role'),
        ),
    ]
