# Generated by Django 3.2.7 on 2021-09-07 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0004_hero_contr_picks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='contr_picks',
        ),
        migrations.AddField(
            model_name='hero',
            name='contr_picks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='heroes.hero'),
        ),
    ]
