# Generated by Django 3.2.7 on 2021-09-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0005_auto_20210907_0816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='contr_picks',
        ),
        migrations.AddField(
            model_name='hero',
            name='contr_picks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_heroes_hero_contr_picks_+', to='heroes.Hero'),
        ),
    ]
