# Generated by Django 3.2.7 on 2021-09-07 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0006_auto_20210907_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hero',
            name='contr_picks',
        ),
        migrations.CreateModel(
            name='ContrPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contr_picks', models.ManyToManyField(related_name='contr_picks_list', to='heroes.Hero')),
                ('hero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contr_picks', to='heroes.hero')),
            ],
        ),
    ]
