# Generated by Django 3.2.7 on 2021-09-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0009_auto_20210907_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrpicks',
            name='contr_picks_list',
        ),
        migrations.RemoveField(
            model_name='contrpicks',
            name='hero',
        ),
        migrations.AddField(
            model_name='herorole',
            name='contr_picks',
            field=models.ManyToManyField(blank=True, null=True, related_name='_heroes_herorole_contr_picks_+', to='heroes.HeroRole'),
        ),
    ]
