# Generated by Django 3.2.7 on 2021-09-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0013_alter_contrpicks_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='pick_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hero',
            name='win_rate',
            field=models.FloatField(default=0),
        ),
    ]
