# Generated by Django 3.2.7 on 2021-09-17 09:46

from django.db import migrations, models
import heroes.models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0014_auto_20210916_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='picture',
            field=models.ImageField(upload_to=heroes.models.hero_picture_directory_path),
        ),
    ]
